[workspace]
resolver = "2"
members = ["crates/server", "crates/db", "crates/proto"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
# 本地依赖
lemma-db = { path = "crates/db" }
lemma-proto = { path = "crates/proto" }
# 远程依赖
axum = "0.8.9"
buffa = { version = "0.8.1", features = ["json"] }
buffa-types = { version = "0.8.1", features = ["json"] }
connectrpc = "0.8.1"
connectrpc-build = "0.8.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sqlx = { version = "0.9.0", features = [
    "postgres",
    "runtime-tokio",
    "tls-rustls",
    "migrate",
] }
tokio = { version = "1.53.1", features = ["full"] }
