name: lemma

services:
  lemma-server:
    build: .
    image: lemma:latest
    profiles: [ "full" ]
    container_name: lemma-server
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${LEMMA_DB_USER:-lemma}:${LEMMA_DB_PASSWORD:?}@lemma-database:5432/${LEMMA_DB:-lemma-db}
      LEMMA_JWT_SECRET: ${LEMMA_JWT_SECRET:?}
      LEMMA_SECRET_KEY: ${LEMMA_SECRET_KEY:?}
      LEMMA_S3_ENDPOINT: http://rustfs:9000
      LEMMA_S3_REGION: ${LEMMA_S3_REGION:-us-east-1}
      LEMMA_S3_BUCKET: ${LEMMA_S3_BUCKET:-lemma}
      LEMMA_S3_ACCESS_KEY_ID: ${LEMMA_S3_ACCESS_KEY_ID:-lemma}
      LEMMA_S3_SECRET_ACCESS_KEY: ${LEMMA_S3_SECRET_ACCESS_KEY:-lemma-secret}
    ports:
      - "1025:1025"
    depends_on:
      lemma-database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:1025/" ]
      interval: 30s
      timeout: 5s
      retries: 3
  lemma-database:
    image: paradedb/paradedb:pg18
    container_name: lemma-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${LEMMA_DB:-lemma-db}
      POSTGRES_USER: ${LEMMA_DB_USER:-lemma}
      POSTGRES_PASSWORD: ${LEMMA_DB_PASSWORD:?please set LEMMA_DB_PASSWORD in .env}
    ports:
      # if you don't want to expose the database to the host, you can comment out the following line
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${LEMMA_DB_USER:-lemma} -d ${LEMMA_DB:-lemma-db}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    command: [ "/data" ]
    environment:
      RUSTFS_ACCESS_KEY: ${LEMMA_S3_ACCESS_KEY_ID:-lemma}
      RUSTFS_SECRET_KEY: ${LEMMA_S3_SECRET_ACCESS_KEY:-lemma-secret}
      RUSTFS_ADDRESS: ":9000"
      RUSTFS_CONSOLE_ADDRESS: ":9001"
      RUSTFS_CONSOLE_ENABLE: "true"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/rustfs:/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rustfs-init:
    image: amazon/aws-cli:latest
    restart: "no"
    depends_on:
      rustfs:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: ${LEMMA_S3_ACCESS_KEY_ID:-lemma}
      AWS_SECRET_ACCESS_KEY: ${LEMMA_S3_SECRET_ACCESS_KEY:-lemma-secret}
      AWS_REGION: ${LEMMA_S3_REGION:-us-east-1}
    entrypoint:
      - sh
      - -c
      - aws s3api create-bucket --bucket ${LEMMA_S3_BUCKET:-lemma} --endpoint-url http://rustfs:9000 || true
