[package]
name = "lemma-proto"
version.workspace = true
edition.workspace = true

[dependencies]
base64.workspace = true
buffa.workspace = true
buffa-types.workspace = true
connectrpc.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
connectrpc-build.workspace = true

[lints]
workspace = true
