[package]
name = "lemma-server"
version.workspace = true
edition.workspace = true

[dependencies]
lemma-db.workspace = true
lemma-proto.workspace = true
lemma-auth.workspace = true
dotenvy.workspace = true
connectrpc = { workspace = true, features = ["axum"] }
axum.workspace = true
tokio.workspace = true
