[package]
version.workspace = true
edition.workspace = true
name = "lemma-server"

[dependencies]
axum.workspace = true
connectrpc.workspace = true
dotenvy.workspace = true
lemma-archive.workspace = true
lemma-auth.workspace = true
lemma-chat.workspace = true
lemma-conversations.workspace = true
lemma-db.workspace = true
lemma-proto.workspace = true
lemma-providers.workspace = true
lemma-sync.workspace = true
rust-embed.workspace = true
tokio.workspace = true

[lints]
workspace = true
